// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Basic: typeof import('./src/components/Basic.vue')['default']
    Computed: typeof import('./src/components/Computed.vue')['default']
    Cycle: typeof import('./src/components/Cycle.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElInput: typeof import('element-plus/es')['ElInput']
    Essential: typeof import('./src/components/Essential.vue')['default']
    Father: typeof import('./src/components/provide/Father.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Refdemo: typeof import('./src/components/Refdemo.vue')['default']
    Son: typeof import('./src/components/provide/Son.vue')['default']
    Sonson: typeof import('./src/components/provide/Sonson.vue')['default']
    Sonsonson: typeof import('./src/components/provide/Sonsonson.vue')['default']
    Transdemo: typeof import('./src/components/Transdemo.vue')['default']
  }
}

export { }
